language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - tree
            - pkg-config
            - libglib2.0-0
            - libglib2.0-dev
before_install:
    - export CC="${CC}"
    - export TEST_PREFIX="$(pwd)/testprefix"
    - test "${TRAVIS_OS_NAME}" = "osx" && chmod -R 755 /usr/local; true
    - test "${TRAVIS_OS_NAME}" = "osx" && brew update; true
    - test "${TRAVIS_OS_NAME}" = "osx" && brew install tree pkg-config glib; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && rm /usr/local/include/c++; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && brew install gcc49; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && ln -s /usr/local/bin/gcc-4.9 /usr/local/bin/gcc; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && ln -s /usr/local/bin/g++-4.9 /usr/local/bin/g++; true
    - test "${TRAVIS_OS_NAME}" = "osx" && test "${CC}" = "gcc" && export PATH="/usr/local/bin:${PATH}"; true
script:
    - make CC="${CC}" PREFIX="${TEST_PREFIX}"
    - make clean
    - make CC="${CC}" PREFIX="${TEST_PREFIX}" WITH_GLIB=1
    - make clean
    - make CC="${CC}" PREFIX="${TEST_PREFIX}" WITH_GLIB=1 WITH_REGEX=1 install
    - make clean
    - tree "${TEST_PREFIX}"
    - rm -r "${TEST_PREFIX}"
